[package]
name = "aptos_synapse"
version = "1.0.0"
authors = ["Aptos Synapse Team"]

[addresses]
aptos_synapse = "_"

[dev-addresses]
aptos_synapse = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]